### ISSUE TITLE
question about setting up config file

### ISSUE THREAD

**Issue by sjw42** [jooh/Dcm2Bids#1]
Hello,
 I'm having some trouble setting up the config file so that it properly handles the field map images in my data set. One of the magnitude fieldmap images only differs from the phase difference image in one field: ImageType": ["ORIGINAL", "PRIMARY", "M", "ND"] vs "ImageType": ["ORIGINAL", "PRIMARY", "P", "ND"]. I cannot seem to get the config file set up so that these are properly differentiated. I tried including statements such as "in": {"ImageType": "'\"P\""} for the former and "in": {"ImageType": "'\"M\""} for the latter in the config file with no luck. The tool is very new to me, so I am probably missing something obvious. Does anyone happen to know where I am going wrong? Thanks very much for any suggestions.
Best regards,
Steve wilson

**Comment by jooh** [comment]
Interesting - I haven't had a chance to convert any fieldmaps yet. I think what you want is something like this criterion for mag:

"equal": {"ImageType":  ["ORIGINAL", "PRIMARY", "M", "ND"]}

And this for phase:

"equal": {"ImageType":  ["ORIGINAL", "PRIMARY", "P", "ND"]}

Let me know if that works.

**Comment by sjw42** [comment]
Thanks so much for the quick and very helpful reply. The statements that you suggested *almost* did the trick. For some reason, I have been unable to get the config file set up so that the two magnitude maps and the phase difference map are all correctly parsed in one pass - I can get any two of the three, but not all three!  The strange thing is that this is true even when I specify the Echo Time that is unique to one of the mag images as a criterion.  In any event, I was able to use your suggestion to put together two config files and a short two-step script that does the trick. Thanks again!
