### ISSUE TITLE
"suffix", "seriesnum"

### ISSUE THREAD

**Issue by gladomat** [jooh/Dcm2Bids#6]
I'm having a hard time understanding "suffix", "seriesnum" and how these should be entered into the example.json file. It would be really awesome if your example.json file would include exmaples of all possible combinations in the descriptions dictionary. I couldn't figure it out.

**Comment by jooh** [comment]
For suffix, I have a more advanced config example here:

https://github.com/jooh/facedistid_analysis/blob/master/facedist_dcm2bids_config.json

I will add it to the repo as well.

In general, the criteria describe intersections (logical and), so a sequence will only be considered a hit if all the criteria in its configuration match.

The 'seriesnum' field is mainly useful if you have multiple acquisitions of the same sequence (E.g., participant moved during mprage so you did it again), and you want to ensure that only one of the acquisitions is included in the BIDS converted dataset.

Probably the best way to clarify this is to update the README. I will have a look.

**Comment by jooh** [comment]
Hopefully resolved by recent commits. Feel free to re-open if anything is still confusing.

29728da14ac4fed34e74c300faac84777dc0838e

014251ceb99b6d942b47d13e56575a7d015ea944
