### ISSUE TITLE
log-file

### ISSUE THREAD

**Issue by landge** [jooh/Dcm2Bids#7]
Hi,
I think you wrote the logger for Dcm2bids, right? Thank you for this very useful extension to dcm2bids.
I was wondering if it's possible to write all the output to one log_file that contains all information.
Sometimes it's difficult to figure out which log_file to use to do some parsing for counting of sequences etc...
Is there an easy solution?

Thanks

**Comment by jooh** [comment]
Log outputs are written to the output directory into a file named dcm2bids.log. Is that what you're after? Not sure if the main repo does this the same way.

**Comment by landge** [comment]
ok, haven't looked into your repo, but the orignial saves the output to multiple files. I will have a look at your version.
Thanks

**Comment by jooh** [comment]
Ah, ok. Yes, my version has diverged a bit. Probably best to think of them as different packages at this point. Feel free to re-open if you have any further issues with my version.
